### ISSUE TITLE
App audio does not work, also users cannot see video of themselves

### ISSUE THREAD

**Issue by CaptainEboy** [videosdk-live/webrtc#6]
After running the app, audio  and video does not work.

Callers cannot hear themselves, also they cannot see video of themselves.

These are the version of the packages i am currently using
"dependencies": {
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-incall-manager": "^4.0.1",
    "react-native-svg": "^13.9.0",
    "react-native-webrtc": "^111.0.0",
    "socket.io-client": "^4.6.1"
  },

**Comment by ahmedbhesaniya97** [comment]
Hi @CaptainEboy,
This project is currently incompatible with the latest version of the `react-native-webrtc` package. To address this issue, you can fork the project and submit a pull request to ensure compatibility with the updated package.

**Comment by CaptainEboy** [comment]
Alright thanks for the feedback.

Would do that now

**Comment by CaptainEboy** [comment]
Hi [ahmedbhesaniya97](https://github.com/ahmedbhesaniya97) i just created a pull request here
https://github.com/videosdk-live/webrtc/pull/7

This is my first time creating a pull request on github so i don't really know how it works

**Comment by Kundannetset** [comment]
Black screen instead of remote stream
