### ISSUE TITLE
hosted server doesn't show any logs and can't be found in the browser

### ISSUE THREAD

**Issue by sana2024** [videosdk-live/webrtc#9]
i tried all the steps in the readme,
i installed the package on my local machine,
run npm install and install socket.io
and run the the project
but nothing appears and it can't be opened in the browser with http://localhost:5000/
i also tried to host it on aws and opened the ports 3000 and 5000 in the security groups but same result,
what am i doing wrong??
any suggestions will be welcomed,
thanks

**Comment by ahmedbhesaniya97** [comment]
Hi @sana2024 
Which App you are referring ?

**Comment by sana2024** [comment]
> Hi @sana2024 Which App you are referring ?

i'm using webrtc-signalling-server with flutter

**Comment by ahmedbhesaniya97** [comment]
CC : @yash-chudasama

**Comment by sana2024** [comment]
> 

for more reference this is what it looks like when i try to run it

![Screen Shot 2023-08-29 at 10 19 29 AM](https://github.com/videosdk-live/webrtc/assets/53705282/fa213fc0-da1b-48d6-a610-dca3347a2b33)

**Comment by sana2024** [comment]
i made it work by adding http listener to the index.js

this is the whole code for anyone who wants it:

`var port = 3000;
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http); // socket.io instance initialization
 
io.use((socket, next) => {
    if (socket.handshake.query) {
      let callerId = socket.handshake.query.callerId;
      socket.user = callerId;
      next();
    }
  });

// listen on the connection event for incoming sockets
io.on('connection', function(socket){
 console.log(socket.user, "Connected");
 socket.join(socket.user);

 socket.on("makeCall", (data) => {
    let calleeId = data.calleeId;
    let sdpOffer = data.sdpOffer;

    socket.to(calleeId).emit("newCall", {
      callerId: socket.user,
      sdpOffer: sdpOffer,
    });
  });
});

socket.on("IceCandidate", (data) => {
    let calleeId = data.calleeId;
    let iceCandidate = data.iceCandidate;

    socket.to(calleeId).emit("IceCandidate", {
      sender: socket.user,
      iceCandidate: iceCandidate,
    });
  });
 
http.listen(port, function(){
 console.log('Signaler listening on *: ', port);
});
`

**Comment by mohamedFouad799** [comment]
@sana2024 when use your code show this error: > webrtc-signalling-server@1.0.0 start
> node index.js

D:\Bayanatz\test_audio\webrtc-signalling-server\index.js:30
socket.on("IceCandidate", (data) => {
^

ReferenceError: socket is not defined
    at Object.<anonymous> (D:\Bayanatz\test_audio\webrtc-signalling-server\index.js:30:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.4.0
